### ISSUE TITLE
Background properties order should not be primarily alphabetical

### ISSUE THREAD

**Issue by Nettsentrisk** [madskristensen/CssSorter#6] opened 2013-05-15 11:54 UTC
To specify a background gradient, the following CSS background stack is necessary:

background: [simple color];
background: [data uri image fallback];
background: -moz-linear-gradient();
background: -webkit-gradient();
background: -webkit-linear-gradient();
background: -o-linear-gradient();
background: -ms-linear-gradient();
background: linear-gradient();

The order is important, especially the W3 recommendation last, the simple color and consequently the image fallback first, and the vendor-prefixed ones in the middle.

Web Essentials now reorders these alphabetically, like this:

background: -moz-linear-gradient();
background: -ms-linear-gradient();
background: -o-linear-gradient();
background: -webkit-gradient();
background: -webkit-linear-gradient();
background: [simple color];
background: linear-gradient();
background: [data uri image fallback];

This might be the case for other types of properties where there is an inherent order that is more important than alphabetical.

**Comment by am11** [comment] 2013-11-05 16:09
Now we have a new list of properties. The precedence follow the order of values defined in [`ValueList`](https://github.com/am11/CssSorter/blob/3ae66ea1a676a9912d50b2aedd748045ac5f44d7/CssSorter/ValueList.cs#L16).

**Comment by am11** [comment] 2013-11-06 08:56
The issue is resolved with #7.

**Closed as completed** 2013-11-06 09:38 UTC
