### ISSUE TITLE
Errors when building solution

### ISSUE THREAD

**Issue by mmoore99** [madskristensen/CssSorter#5] opened 2013-02-11 23:21 UTC
Since commit b88f9a3 I get errors when trying to build the solution (see screenshot below):

![CssSorter](https://f.cloud.github.com/assets/45022/147098/8ae5f798-74a1-11e2-9238-1b86e9562ff8.png)

**Comment by am11** [comment] 2013-11-05 16:03
The assembly path are updated in `csproj` file. The issue is resolved with #7.

**Closed as completed** 2013-11-06 06:58 UTC
